In [1]:
from pathlib import Path
import pickle
wychoffs_enumerated_by_ss_file = "wychoffs_enumerated_by_ss.pkl.gz"
with open(wychoffs_enumerated_by_ss_file, "rb") as f:
    enum_from_ss_letter, letter_from_ss_enum, ss_from_letter = pickle.load(f)

In [2]:
from mp_20_utils import load_all_data
dataset = "mp_20_biternary"
datasets_pd, torch_datasets, site_to_ids, element_to_ids, spacegroup_to_ids, max_len, max_enumeration, enumeration_stop, enumeration_pad = load_all_data(
    dataset=dataset)

mp_20_biternary cache <function cache_tensors at 0x7f9519413760>


In [3]:
datasets_pd['train']

material_id  formation_energy_per_atom  band_gap pretty_formula  \
19480   mp-974729                  -0.314759    0.0000     Nd(Al2Cu)4   
29624  mp-1185360                  -0.193761    0.0000        LiMnIr2   
10889   mp-677272                  -2.474759    0.4707        La2EuS4   
6575   mp-1104517                  -0.641076    0.0000      Yb3Ga9Pt2   
34946   mp-777964                  -1.697508    0.0000        Na2BiO3   
...           ...                        ...       ...            ...   
37856   mp-568116                  -0.988502    3.7614      Lu2(CN2)3   
11955   mp-865529                  -0.640955    0.0000        Ti2NiIr   
26119  mp-1189241                  -0.756019    0.0000        GdAs2Au   
30556  mp-1104538                  -0.104870    0.0000      Tm(FeSn)6   
32933   mp-756354                  -3.712252    2.7684        SrSc2O4   

       e_above_hull            elements  spacegroup.number  \
19480      0.000000  ['Al', 'Cu', 'Nd']                139   
29624      0.018075  ['Ir', 'Li', 'Mn']                225   
10889      0.000000   ['Eu', 'La', 'S']                122   
6575       0.000000  ['Ga', 'Pt', 'Yb']                 71   
34946      0.033273   ['Bi', 'Na', 'O']                 12   
...             ...                 ...                ...   
37856      0.045185    ['C', 'Lu', 'N']                155   
11955      0.000000  ['Ti', 'Ni', 'Ir']                225   
26119      0.010305  ['As', 'Au', 'Gd']                 64   
30556      0.021206  ['Fe', 'Sn', 'Tm']                191   
32933      0.025978   ['O', 'Sc', 'Sr']                 63   

                                               structure  \
19480  [[0. 0. 0.] Nd, [-0.63352833  2.24470901  4.53...   
29624  [[2.40433095 1.70011872 4.16442336] Li, [0. 0....   
10889  [[ 3.58443254  1.52637135 -1.25794367] La, [2....   
6575   [[ 3.48277839  2.03085438 -4.69974507] Yb, [ 1...   
34946  [[4.45184852 0.7871356  3.99498878] Na, [-1.74...   
...                                                  ...   
37856  [[1.23035284 0.87512562 2.09829693] Lu, [ 5.91...   
11955  [[1.25066496 0.88435368 2.16621526] Ti, [3.751...   
26119  [[1.06082864 1.06340362 7.8483794 ] Gd, [ 2.97...   
30556  [[0. 0. 0.] Tm, [1.352999   2.34346301 6.72622...   
32933  [[4.40088431 0.33759565 2.6714    ] Sr, [-3.46...   

                            symmetry_sites         symmetry_elements  \
19480           [4/mmm, m2m., m2m., ..2/m]          [Nd, Al, Al, Cu]   
29624                   [m-3m, m-3m, -43m]              [Li, Mn, Ir]   
10889                       [.2., -4.., 1]               [La, Eu, S]   
6575        [mmm, mm2, mmm, m.., m.., m2m]  [Yb, Yb, Ga, Ga, Ga, Pt]   
34946               [2/m, 2/m, 2, 2, m, 1]    [Na, Na, Na, Bi, O, O]   
...                                    ...                       ...   
37856                           [3., 1, 1]                [Lu, C, N]   
11955                   [-43m, m-3m, m-3m]              [Ti, Ni, Ir]   
26119                 [m.., m.., 2.., .2.]          [Gd, As, As, Au]   
30556  [6/mm2/m, 2m., -622m2, 6mm, -622m2]      [Tm, Fe, Sn, Sn, Sn]   
32933          [m2m, m.., 2/m.., m2m, m..]         [Sr, Sc, O, O, O]   

      symmetry_multiplicity    symmetry_letters symmetry_sites_enumeration  \
19480          [2, 8, 8, 8]        [a, i, j, f]               [0, 0, 1, 0]   
29624             [4, 4, 8]           [b, a, c]                  [1, 0, 0]   
10889            [8, 4, 16]           [d, a, e]                  [0, 0, 0]   
6575     [2, 4, 2, 8, 8, 4]  [c, i, b, l, l, g]         [2, 0, 1, 0, 0, 0]   
34946    [2, 2, 4, 4, 4, 8]  [a, d, h, g, i, j]         [0, 3, 1, 0, 0, 0]   
...                     ...                 ...                        ...   
37856            [6, 9, 18]           [c, d, f]                  [0, 0, 2]   
11955             [8, 4, 4]           [c, a, b]                  [0, 0, 1]   
26119          [8, 8, 8, 8]        [f, f, d, e]               [0, 0, 0, 0]   
30556       [1, 6,

In [11]:
import torch
augmented_field = "symmetry_sites_enumeration"
dtype=torch.long
device='cpu'
symmetry_aug_padded = torch.nested.nested_tensor(
            torch_datasets["train"][f"{augmented_field}_augmented"], dtype=dtype, device=device).to_padded_tensor(
            padding=100)

In [36]:
symmetry_aug_nested = torch.nested.nested_tensor(
            torch_datasets["train"][f"{augmented_field}_augmented"], dtype=dtype, device=device)

In [48]:
symmetry_aug_nested.to_sparse()

NotImplementedError: Could not run 'aten::_to_sparse' with arguments from the 'NestedTensorCPU' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::_to_sparse' is only available for these backends: [CPU, CUDA, Meta, SparseCPU, SparseCUDA, SparseCsrCPU, SparseCsrCUDA, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradHIP, AutogradXLA, AutogradMPS, AutogradIPU, AutogradXPU, AutogradHPU, AutogradVE, AutogradLazy, AutogradMTIA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, AutogradMeta, AutogradNestedTensor, Tracer, AutocastCPU, AutocastXPU, AutocastCUDA, FuncTorchBatched, BatchedNestedTensor, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PreDispatch, PythonDispatcher].

CPU: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCPU.cpp:31509 [kernel]
CUDA: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCUDA.cpp:44648 [kernel]
Meta: registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/core/MetaFallbackKernel.cpp:23 [backend fallback]
SparseCPU: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterSparseCPU.cpp:1387 [kernel]
SparseCUDA: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterSparseCUDA.cpp:1573 [kernel]
SparseCsrCPU: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterSparseCsrCPU.cpp:1135 [kernel]
SparseCsrCUDA: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterSparseCsrCUDA.cpp:1276 [kernel]
BackendSelect: fallthrough registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/core/PythonFallbackKernel.cpp:153 [backend fallback]
FuncTorchDynamicLayerBackMode: registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/functorch/DynamicLayer.cpp:497 [backend fallback]
Functionalize: registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/FunctionalizeFallbackKernel.cpp:349 [backend fallback]
Named: registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
Conjugate: registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/ConjugateFallback.cpp:17 [backend fallback]
Negative: registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/native/NegateFallback.cpp:18 [backend fallback]
ZeroTensor: registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/ZeroTensorFallback.cpp:86 [backend fallback]
ADInplaceOrView: fallthrough registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/core/VariableFallbackKernel.cpp:86 [backend fallback]
AutogradOther: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:19469 [autograd kernel]
AutogradCPU: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:19469 [autograd kernel]
AutogradCUDA: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:19469 [autograd kernel]
AutogradHIP: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:19469 [autograd kernel]
AutogradXLA: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:19469 [autograd kernel]
AutogradMPS: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:19469 [autograd kernel]
AutogradIPU: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:19469 [autograd kernel]
AutogradXPU: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:19469 [autograd kernel]
AutogradHPU: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:19469 [autograd kernel]
AutogradVE: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:19469 [autograd kernel]
AutogradLazy: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:19469 [autograd kernel]
AutogradMTIA: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:19469 [autograd kernel]
AutogradPrivateUse1: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:19469 [autograd kernel]
AutogradPrivateUse2: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:19469 [autograd kernel]
AutogradPrivateUse3: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:19469 [autograd kernel]
AutogradMeta: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:19469 [autograd kernel]
AutogradNestedTensor: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/VariableType_3.cpp:19469 [autograd kernel]
Tracer: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/TraceType_3.cpp:14774 [kernel]
AutocastCPU: fallthrough registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/autocast_mode.cpp:209 [backend fallback]
AutocastXPU: fallthrough registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/autocast_mode.cpp:351 [backend fallback]
AutocastCUDA: fallthrough registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/autocast_mode.cpp:165 [backend fallback]
FuncTorchBatched: registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/functorch/LegacyBatchingRegistrations.cpp:731 [backend fallback]
BatchedNestedTensor: registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/functorch/LegacyBatchingRegistrations.cpp:758 [backend fallback]
FuncTorchVmapMode: fallthrough registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/functorch/VmapModeRegistrations.cpp:27 [backend fallback]
Batched: registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/LegacyBatchingRegistrations.cpp:1075 [backend fallback]
VmapMode: fallthrough registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
FuncTorchGradWrapper: registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/functorch/TensorWrapper.cpp:207 [backend fallback]
PythonTLSSnapshot: registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/core/PythonFallbackKernel.cpp:161 [backend fallback]
FuncTorchDynamicLayerFrontMode: registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/functorch/DynamicLayer.cpp:493 [backend fallback]
PreDispatch: registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/core/PythonFallbackKernel.cpp:165 [backend fallback]
PythonDispatcher: registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/core/PythonFallbackKernel.cpp:157 [backend fallback]


In [14]:
symmetry_aug_padded.shape

torch.Size([21317, 48, 21])

In [52]:
def randint_tensor(high: torch.Tensor):
    dtype = high.dtype
    return torch.randint(torch.iinfo(dtype).max, size=(len(high),), device=high.device) % high

In [17]:
augmentation_options = torch.tensor(
            list(map(len, torch_datasets["train"][f"{augmented_field}_augmented"])), dtype=dtype, device=device)


In [18]:
from wyckoff_transformer import randint_tensor

In [20]:
selection = randint_tensor(augmentation_options)

In [22]:
symmetry_aug_padded.shape

torch.Size([21317, 48, 21])

In [35]:
symmetry_aug_padded[torch.arange(len(symmetry_aug_padded)), selection].shape

torch.Size([21317, 21])

In [32]:
print(symmetry_aug_padded.shape)
print(selection.shape)
for i in range(10):
    print(selection[i])
    print(symmetry_aug_padded[i, selection[i], :])

torch.Size([21317, 48, 21])
torch.Size([21317])
tensor(1)
tensor([0, 0, 1, 0, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9])
tensor(1)
tensor([0, 1, 0, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9])
tensor(1)
tensor([0, 1, 0, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9])
tensor(18)
tensor([0, 0, 2, 0, 0, 1, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9])
tensor(0)
tensor([0, 3, 1, 0, 0, 0, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9])
tensor(1)
tensor([0, 0, 0, 0, 0, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9])
tensor(4)
tensor([2, 0, 1, 0, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9])
tensor(0)
tensor([0, 0, 0, 0, 0, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9])
tensor(0)
tensor([0, 1, 1, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9])
tensor(1)
tensor([1, 1, 1, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9])


In [ ]:
from pyxtal import Group
Group(63).get_alternatives()['Transformed WP']

['a b c d e f g h', 'b a c d e f g h', 'a b c d e f g h', 'b a c d e f g h']

In [ ]:
for wp in Group(63).Wyckoff_positions[::-1]:
    print(wp.letter)

a
b
c
d
e
f
g
h


In [ ]:
type(Group(63).Wyckoff_positions)

list

In [ ]:
from preprocess_wychoffs import prepare_augmentation_dict

In [ ]:
prepare_augmentation_dict()

{1: [{'a': 'a'}],
 2: [{'a': 'c',
   'b': 'g',
   'c': 'a',
   'd': 'e',
   'e': 'd',
   'f': 'h',
   'g': 'b',
   'h': 'f',
   'i': 'i'},
  {'a': 'g',
   'b': 'c',
   'c': 'b',
   'd': 'h',
   'e': 'f',
   'f': 'e',
   'g': 'a',
   'h': 'd',
   'i': 'i'},
  {'a': 'a',
   'b': 'b',
   'c': 'c',
   'd': 'd',
   'e': 'e',
   'f': 'f',
   'g': 'g',
   'h': 'h',
   'i': 'i'},
  {'a': 'b',
   'b': 'a',
   'c': 'g',
   'd': 'f',
   'e': 'h',
   'f': 'd',
   'g': 'c',
   'h': 'e',
   'i': 'i'},
  {'a': 'e',
   'b': 'h',
   'c': 'd',
   'd': 'c',
   'e': 'a',
   'f': 'g',
   'g': 'f',
   'h': 'b',
   'i': 'i'},
  {'a': 'f',
   'b': 'd',
   'c': 'h',
   'd': 'b',
   'e': 'g',
   'f': 'a',
   'g': 'e',
   'h': 'c',
   'i': 'i'},
  {'a': 'd',
   'b': 'f',
   'c': 'e',
   'd': 'a',
   'e': 'c',
   'f': 'b',
   'g': 'h',
   'h': 'g',
   'i': 'i'},
  {'a': 'h',
   'b': 'e',
   'c': 'f',
   'd': 'g',
   'e': 'b',
   'f': 'c',
   'g': 'd',
   'h': 'a',
   'i': 'i'}],
 3: [{'a': 'a', 'b': 'b', 'c': 'c'

In [ ]:
from pyxtal import Group
Group(1).get_alternatives()

{'No.': ['1', '2'],
 'Coset Representative': ['x,y,z', '-x,-y,-z'],
 'Geometrical Interpretation': ['1', '-1 0,0,0'],
 'Transformed WP': ['a', 'a']}

In [ ]:
augmenentation[0]

tensor(indices=tensor([[ 0,  1],
                       [11, 11],
                       [ 0,  0]]),
       values=tensor([0, 0]),
       size=(2, 12, 1), nnz=2, layout=torch.sparse_coo)

In [ ]:
import torch

In [ ]:
augmenentation[0][0, 11, [0, 0]]

NotImplementedError: Could not run 'aten::index.Tensor' with arguments from the 'SparseCPU' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::index.Tensor' is only available for these backends: [CPU, CUDA, HIP, MPS, IPU, XPU, HPU, VE, MTIA, PrivateUse1, PrivateUse2, PrivateUse3, Meta, FPGA, MAIA, Vulkan, Metal, QuantizedCPU, QuantizedCUDA, QuantizedHIP, QuantizedMPS, QuantizedIPU, QuantizedXPU, QuantizedHPU, QuantizedVE, QuantizedMTIA, QuantizedPrivateUse1, QuantizedPrivateUse2, QuantizedPrivateUse3, QuantizedMeta, CustomRNGKeyId, MkldnnCPU, SparseCsrCPU, SparseCsrCUDA, SparseCsrHIP, SparseCsrMPS, SparseCsrIPU, SparseCsrXPU, SparseCsrHPU, SparseCsrVE, SparseCsrMTIA, SparseCsrPrivateUse1, SparseCsrPrivateUse2, SparseCsrPrivateUse3, SparseCsrMeta, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradHIP, AutogradXLA, AutogradMPS, AutogradIPU, AutogradXPU, AutogradHPU, AutogradVE, AutogradLazy, AutogradMTIA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, AutogradMeta, AutogradNestedTensor, Tracer, AutocastCPU, AutocastXPU, AutocastCUDA, FuncTorchBatched, BatchedNestedTensor, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PreDispatch, PythonDispatcher].

Undefined: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
CPU: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCPU.cpp:31509 [kernel]
CUDA: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCUDA.cpp:44648 [kernel]
HIP: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
MPS: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
IPU: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
XPU: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
HPU: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
VE: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
MTIA: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
PrivateUse1: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
PrivateUse2: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
PrivateUse3: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
Meta: registered at /dev/null:241 [kernel]
FPGA: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
MAIA: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
Vulkan: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
Metal: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
QuantizedCPU: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterQuantizedCPU.cpp:951 [kernel]
QuantizedCUDA: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
QuantizedHIP: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
QuantizedMPS: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
QuantizedIPU: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
QuantizedXPU: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
QuantizedHPU: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
QuantizedVE: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
QuantizedMTIA: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
QuantizedPrivateUse1: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
QuantizedPrivateUse2: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
QuantizedPrivateUse3: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
QuantizedMeta: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
CustomRNGKeyId: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
MkldnnCPU: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
SparseCsrCPU: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
SparseCsrCUDA: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
SparseCsrHIP: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
SparseCsrMPS: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
SparseCsrIPU: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
SparseCsrXPU: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
SparseCsrHPU: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
SparseCsrVE: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
SparseCsrMTIA: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
SparseCsrPrivateUse1: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
SparseCsrPrivateUse2: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
SparseCsrPrivateUse3: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
SparseCsrMeta: registered at /home/kna/WyckoffTransformer/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21612 [default backend kernel]
BackendSelect: fallthrough registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/core/PythonFallbackKernel.cpp:153 [backend fallback]
FuncTorchDynamicLayerBackMode: registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/functorch/DynamicLayer.cpp:497 [backend fallback]
Functionalize: registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/FunctionalizeFallbackKernel.cpp:349 [backend fallback]
Named: registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
Conjugate: registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/ConjugateFallback.cpp:17 [backend fallback]
Negative: registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/native/NegateFallback.cpp:18 [backend fallback]
ZeroTensor: registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/ZeroTensorFallback.cpp:86 [backend fallback]
ADInplaceOrView: fallthrough registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/core/VariableFallbackKernel.cpp:86 [backend fallback]
AutogradOther: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:16862 [autograd kernel]
AutogradCPU: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:16862 [autograd kernel]
AutogradCUDA: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:16862 [autograd kernel]
AutogradHIP: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:16862 [autograd kernel]
AutogradXLA: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:16862 [autograd kernel]
AutogradMPS: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:16862 [autograd kernel]
AutogradIPU: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:16862 [autograd kernel]
AutogradXPU: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:16862 [autograd kernel]
AutogradHPU: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:16862 [autograd kernel]
AutogradVE: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:16862 [autograd kernel]
AutogradLazy: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:16862 [autograd kernel]
AutogradMTIA: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:16862 [autograd kernel]
AutogradPrivateUse1: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:16862 [autograd kernel]
AutogradPrivateUse2: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:16862 [autograd kernel]
AutogradPrivateUse3: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:16862 [autograd kernel]
AutogradMeta: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:16862 [autograd kernel]
AutogradNestedTensor: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:16862 [autograd kernel]
Tracer: registered at /home/kna/WyckoffTransformer/pytorch/torch/csrc/autograd/generated/TraceType_1.cpp:16059 [kernel]
AutocastCPU: fallthrough registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/autocast_mode.cpp:209 [backend fallback]
AutocastXPU: fallthrough registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/autocast_mode.cpp:351 [backend fallback]
AutocastCUDA: fallthrough registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/autocast_mode.cpp:165 [backend fallback]
FuncTorchBatched: registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/functorch/BatchRulesScatterOps.cpp:1216 [kernel]
BatchedNestedTensor: registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/functorch/LegacyBatchingRegistrations.cpp:758 [backend fallback]
FuncTorchVmapMode: fallthrough registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/functorch/VmapModeRegistrations.cpp:27 [backend fallback]
Batched: registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/LegacyBatchingRegistrations.cpp:1075 [backend fallback]
VmapMode: fallthrough registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
FuncTorchGradWrapper: registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/functorch/TensorWrapper.cpp:207 [backend fallback]
PythonTLSSnapshot: registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/core/PythonFallbackKernel.cpp:161 [backend fallback]
FuncTorchDynamicLayerFrontMode: registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/functorch/DynamicLayer.cpp:493 [backend fallback]
PreDispatch: registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/core/PythonFallbackKernel.cpp:165 [backend fallback]
PythonDispatcher: registered at /home/kna/WyckoffTransformer/pytorch/aten/src/ATen/core/PythonFallbackKernel.cpp:157 [backend fallback]


In [ ]:
spacegroup_to_ids[1]

0

In [ ]:
site_to_ids['1']

11