In [105]:
from wyckoff_transformer.tokenization import load_tensors_and_tokenisers

tensors, tokenisers, token_engineers = load_tensors_and_tokenisers("matbench_discovery", "sg_scalars")

In [111]:
len(tensors['train']['site_symmetries'])

145923

In [112]:
len(tensors['val']['site_symmetries'])

256963

In [2]:
from pyxtal import Group

In [3]:
g = Group(162)

In [4]:
import numpy as np
def check_group(group_number):
    group = Group(group_number)
    last_site_symmetry = None
    last_distace = None
    for wyckoff_position in group:
        wyckoff_position.get_site_symmetry()
        this_distance = np.linalg.norm(wyckoff_position.ops[0].affine_matrix[:3, 3])
        #print(wyckoff_position.site_symm, this_distance)
        if wyckoff_position.site_symm == last_site_symmetry:
            if this_distance > last_distance:
                print(f"Group {group_number} has a Wyckoff position with site symmetry {wyckoff_position.site_symm} that is not ordered by distance")
        last_site_symmetry = wyckoff_position.site_symm
        last_distance = this_distance

In [5]:
for i in range(1, 231):
    check_group(i)

Group 13 has a Wyckoff position with site symmetry -1 that is not ordered by distance
Group 15 has a Wyckoff position with site symmetry -1 that is not ordered by distance
Group 21 has a Wyckoff position with site symmetry ..2 that is not ordered by distance
Group 21 has a Wyckoff position with site symmetry 222 that is not ordered by distance
Group 22 has a Wyckoff position with site symmetry 222 that is not ordered by distance
Group 37 has a Wyckoff position with site symmetry ..2 that is not ordered by distance
Group 47 has a Wyckoff position with site symmetry mmm that is not ordered by distance
Group 48 has a Wyckoff position with site symmetry -1 that is not ordered by distance
Group 49 has a Wyckoff position with site symmetry ..2 that is not ordered by distance
Group 49 has a Wyckoff position with site symmetry ..2/m that is not ordered by distance
Group 50 has a Wyckoff position with site symmetry 222 that is not ordered by distance
Group 53 has a Wyckoff position with site sy

In [105]:
Group(48)[7]

Wyckoff position 4f in space group 48 with site symmetry -1
0, 0, 0
1/2, 1/2, 0
1/2, 0, 1/2
0, 1/2, 1/2

In [106]:
Group(48)[8]

Wyckoff position 4e in space group 48 with site symmetry -1
1/2, 1/2, 1/2
0, 0, 1/2
0, 1/2, 0
1/2, 0, 0

In [102]:
all_ops = np.array([[o.affine_matrix[:3, 3] for o in w.ops] for w in Group(48)[7:9]])

In [112]:
all_ops.mean(axis=0)

array([[0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25]])

In [128]:
all_ops

array([[[0. , 0. , 0. ],
        [0.5, 0.5, 0. ],
        [0.5, 0. , 0.5],
        [0. , 0.5, 0.5]],

       [[0.5, 0.5, 0.5],
        [0. , 0. , 0.5],
        [0. , 0.5, 0. ],
        [0.5, 0. , 0. ]]])

In [137]:
all_ops - all_ops[0]

array([[[ 0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ]],

       [[ 0.5,  0.5,  0.5],
        [-0.5, -0.5,  0.5],
        [-0.5,  0.5, -0.5],
        [ 0.5, -0.5, -0.5]]])

In [136]:
np.linalg.norm(all_ops, axis=2)

array([[0.        , 0.70710678, 0.70710678, 0.70710678],
       [0.8660254 , 0.5       , 0.5       , 0.5       ]])

In [134]:
np.linalg.norm(all_ops, axis=2).mean(axis=1)

array([0.53033009, 0.59150635])

In [109]:
all_ops - all_ops.mean(axis=0)

array([[[-0.25, -0.25, -0.25],
        [ 0.25,  0.25, -0.25],
        [ 0.25, -0.25,  0.25],
        [-0.25,  0.25,  0.25]],

       [[ 0.25,  0.25,  0.25],
        [-0.25, -0.25,  0.25],
        [-0.25,  0.25, -0.25],
        [ 0.25, -0.25, -0.25]]])

In [119]:
(all_ops - all_ops.mean(axis=0)).mean(axis=1)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [96]:
(all_ops - all_ops[-1]).std(axis=1)

array([[0.25, 0.  , 0.5 ],
       [0.25, 0.  , 0.  ],
       [0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  ]])

In [61]:
refernce_ops = np.array([o.affine_matrix[:3, 3] for o in Group(49)[-1].ops])

In [62]:
refernce_ops

array([[0. , 0. , 0. ],
       [0. , 0. , 0.5]])

In [55]:
new_ops = np.array([o.affine_matrix[:3, 3] for o in Group(49)[-2].ops])

In [56]:
shifted_ops = new_ops - refernce_ops

In [58]:
shifted_ops

array([[0.5, 0.5, 0. ],
       [0.5, 0.5, 0. ]])

In [60]:
(shifted_ops == shifted_ops[0])

array([[ True,  True,  True],
       [ True,  True,  True]])

In [51]:
shifted_ops

array([[[ 0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ]],

       [[-0.5,  0.5,  0. ],
        [-0.5,  0.5,  0. ]],

       [[ 0. ,  0.5,  0. ],
        [ 0. ,  0.5,  0. ]],

       [[-0.5,  0. ,  0. ],
        [-0.5,  0. ,  0. ]]])

In [53]:
shifted_ops[1]

array([[-0.5,  0.5,  0. ],
       [-0.5,  0.5,  0. ]])

In [50]:
(shifted_ops == np.expand_dims(shifted_ops[:, 0], 1)).all()

True

In [139]:
Group(15)

-- Spacegroup --# 15 (C2/c)--
8f	site symm: 1
4e	site symm: 2
4d	site symm: -1
4c	site symm: -1
4b	site symm: -1
4a	site symm: -1

In [143]:
np.array([[o.affine_matrix[:3, 3] for o in w.ops] for w in Group(15)[2:]])

array([[[0.25, 0.25, 0.5 ],
        [0.75, 0.25, 0.  ],
        [0.75, 0.75, 0.5 ],
        [1.25, 0.75, 0.  ]],

       [[0.25, 0.25, 0.  ],
        [0.75, 0.25, 0.5 ],
        [0.75, 0.75, 0.  ],
        [1.25, 0.75, 0.5 ]],

       [[0.  , 0.5 , 0.  ],
        [0.  , 0.5 , 0.5 ],
        [0.5 , 1.  , 0.  ],
        [0.5 , 1.  , 0.5 ]],

       [[0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.5 ],
        [0.5 , 0.5 , 0.  ],
        [0.5 , 0.5 , 0.5 ]]])

In [160]:
Group(15)[2][0].affine_matrix

array([[0.  , 0.  , 0.  , 0.25],
       [0.  , 0.  , 0.  , 0.25],
       [0.  , 0.  , 0.  , 0.5 ],
       [0.  , 0.  , 0.  , 1.  ]])

In [162]:
Group(15)[2][1].affine_matrix

array([[0.  , 0.  , 0.  , 0.75],
       [0.  , 0.  , 0.  , 0.25],
       [0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 1.  ]])

In [163]:
Group(15)[2][2].affine_matrix

array([[0.  , 0.  , 0.  , 0.75],
       [0.  , 0.  , 0.  , 0.75],
       [0.  , 0.  , 0.  , 0.5 ],
       [0.  , 0.  , 0.  , 1.  ]])

In [165]:
Group(15)[3][0].affine_matrix

array([[0.  , 0.  , 0.  , 0.25],
       [0.  , 0.  , 0.  , 0.25],
       [0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 1.  ]])

In [168]:
Group(45)[2][1].affine_matrix

array([[0. , 0. , 0. , 0.5],
       [0. , 0. , 0. , 0.5],
       [0. , 0. , 1. , 0. ],
       [0. , 0. , 0. , 1. ]])

In [151]:
w=Group(15)[4]

In [155]:
w.get_site_symmetry()

In [ ]:
w.

AttributeError: 'Wyckoff_position' object has no attribute 'coords'

In [150]:
Group(15)

-- Spacegroup --# 15 (C2/c)--
8f	site symm: 1
4e	site symm: 2
4d	site symm: -1
4c	site symm: -1
4b	site symm: -1
4a	site symm: -1

In [98]:
Group(13)[-3].ops[0].affine_matrix

array([[0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.5],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 1. ]])

In [100]:
Group(13)

-- Spacegroup --# 13 (P2/c)--
4g	site symm: 1
2f	site symm: 2
2e	site symm: 2
2d	site symm: -1
2c	site symm: -1
2b	site symm: -1
2a	site symm: -1

In [89]:
Group(13)[7]

IndexError: list index out of range

In [38]:
g[3].ops[0].affine_matrix

array([[ 1.,  0.,  0.,  0.],
       [-1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [34]:
g[2].ops

[SymmOp(self.affine_matrix=array([[ 1. ,  0. ,  0. ,  0. ],
        [-1. ,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ,  0.5],
        [ 0. ,  0. ,  0. ,  1. ]])),
 SymmOp(self.affine_matrix=array([[1. , 0. , 0. , 0. ],
        [2. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0.5],
        [0. , 0. , 0. , 1. ]])),
 SymmOp(self.affine_matrix=array([[-2. ,  0. ,  0. ,  0. ],
        [-1. ,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ,  0.5],
        [ 0. ,  0. ,  0. ,  1. ]])),
 SymmOp(self.affine_matrix=array([[-1. ,  0. ,  0. ,  0. ],
        [ 1. ,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ,  0.5],
        [ 0. ,  0. ,  0. ,  1. ]])),
 SymmOp(self.affine_matrix=array([[-1. ,  0. ,  0. ,  0. ],
        [-2. ,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ,  0.5],
        [ 0. ,  0. ,  0. ,  1. ]])),
 SymmOp(self.affine_matrix=array([[2. , 0. , 0. , 0. ],
        [1. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0.5],
        [0. , 0. , 0. , 1. ]]))]

In [27]:
s.ops[0]

SymmOp(self.affine_matrix=array([[1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]]))

In [25]:
g[-2].get_euclidean_generator()

TypeError: Wyckoff_position.get_euclidean_generator() missing 1 required positional argument: 'cell'

In [18]:
s.project((1,1,1))

array([0., 0., 0.])

In [101]:
s.ops

[SymmOp(self.affine_matrix=array([[0.        , 0.        , 0.        , 0.33333333],
        [0.        , 0.        , 0.        , 0.66666667],
        [0.        , 0.        , 0.        , 0.5       ],
        [0.        , 0.        , 0.        , 1.        ]])),
 SymmOp(self.affine_matrix=array([[0.        , 0.        , 0.        , 0.66666667],
        [0.        , 0.        , 0.        , 0.33333333],
        [0.        , 0.        , 0.        , 0.5       ],
        [0.        , 0.        , 0.        , 1.        ]]))]

In [103]:
g[-2].ops

[SymmOp(self.affine_matrix=array([[0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0.5],
        [0. , 0. , 0. , 1. ]]))]

In [104]:
g[-1].ops

[SymmOp(self.affine_matrix=array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 1.]]))]

In [62]:
g[-3].ops

[SymmOp(self.affine_matrix=array([[0.        , 0.        , 0.        , 0.33333333],
        [0.        , 0.        , 0.        , 0.66666667],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 1.        ]])),
 SymmOp(self.affine_matrix=array([[0.        , 0.        , 0.        , 0.66666667],
        [0.        , 0.        , 0.        , 0.33333333],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 1.        ]]))]

In [ ]:
g[-4].

[SymmOp(self.affine_matrix=array([[0.        , 0.        , 0.        , 0.33333333],
        [0.        , 0.        , 0.        , 0.66666667],
        [0.        , 0.        , 0.        , 0.5       ],
        [0.        , 0.        , 0.        , 1.        ]])),
 SymmOp(self.affine_matrix=array([[0.        , 0.        , 0.        , 0.66666667],
        [0.        , 0.        , 0.        , 0.33333333],
        [0.        , 0.        , 0.        , 0.5       ],
        [0.        , 0.        , 0.        , 1.        ]]))]

In [39]:
g[-2].get_site_symmetry_object().to_one_hot()

array([[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [178]:
Group(93)[4][0].affine_matrix

array([[1. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.5],
       [0. , 0. , 0. , 1. ]])

In [187]:
Group(93)[4][3].affine_matrix

array([[ 0.,  0.,  0.,  0.],
       [-1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [180]:
Group(93)[6][0].affine_matrix

array([[1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [190]:
t = Group(93)[6][-1]

In [192]:
t.operate((0,0,0))

array([0. , 0. , 0.5])

In [195]:
t((0,0,0))

TypeError: 'SymmOp' object is not callable

In [189]:
Group(93)[4]

Wyckoff position 4l in space group 93 with site symmetry .2.
x, 0, 1/2
-x, 0, 1/2
0, x, 0
0, -x, 0

In [208]:
Group(150)

-- Spacegroup --# 150 (P321)--
6g	site symm: 1
3f	site symm: 1
3e	site symm: 1
2d	site symm: 3..
2c	site symm: 3..
1b	site symm: 32.
1a	site symm: 32.

In [198]:
Group(150)[0]

Wyckoff position 6g in space group 150 with site symmetry 1
x, y, z
-y, x-y, z
-x+y, -x, z
y, x, -z
x-y, -y, -z
-x, -x+y, -z

In [217]:
w=Group(150)[1]

In [218]:
w.get_site_symmetry()

In [220]:
w.multiplicity

3

In [222]:
w

Wyckoff position 3f in space group 150 with site symmetry 1
x, 0, 1/2
0, x, 1/2
-x, -x, 1/2

In [225]:
Group(194)

-- Spacegroup --# 194 (P63/mmc)--
24l	site symm: 1
12k	site symm: 1
12j	site symm: m..
12i	site symm: 1
6h	site symm: m2.
6g	site symm: -1
4f	site symm: 3m.
4e	site symm: 3m.
2d	site symm: -622m2
2c	site symm: -622m2
2b	site symm: -622m2
2a	site symm: -32/m.

In [228]:
w=Group(194)[1]
w.get_site_symmetry()

In [229]:
w

Wyckoff position 12k in space group 194 with site symmetry 1
x, 2x, z
-2x, -x, z
x, -x, z
-x, -2x, z+1/2
2x, x, z+1/2
-x, x, z+1/2
2x, x, -z
-x, -2x, -z
-x, x, -z
-2x, -x, -z+1/2
x, 2x, -z+1/2
x, -x, -z+1/2

In [230]:
w.multiplicity

12

In [214]:
Group(89)

-- Spacegroup --# 89 (P422)--
8p	site symm: 1
4o	site symm: .2.
4n	site symm: .2.
4m	site symm: .2.
4l	site symm: .2.
4k	site symm: ..2
4j	site symm: ..2
4i	site symm: 2..
2h	site symm: 4..
2g	site symm: 4..
2f	site symm: 222.
2e	site symm: 222.
1d	site symm: 422
1c	site symm: 422
1b	site symm: 422
1a	site symm: 422

In [231]:
import gzip
import pickle

In [232]:
with gzip.open("cache/wychoffs_enumerated_by_ss.pkl.gz", 'rb') as f:
    enum_from_ss_letter, letter_from_ss_enum, ss_from_letter = pickle.load(f)

In [233]:
with gzip.open("cache/engineers/multiplicity.pkl.gz", 'rb') as f:
    multiplicity = pickle.load(f)

In [ ]:
multiplicity.db.loc[190]

site_symmetries  sites_enumeration
32.              0                     2
-6..             0                     2
                 1                     2
                 2                     2
3..              0                     4
                 1                     4
.2.              0                     6
m..              0                     6
1                0                    12
Name: multiplicity, dtype: int64